version: "3.8"
name: wire-vpn
services:
  admin-bot:
    environment:
        - TELEGRAM_API_TOKEN=${TELEGRAM_API_TOKEN}
        - TELEGRAM_USERNAME=${TELEGRAM_USERNAME}
        - VPN_ADMIN_URL=${VPN_ADMIN_URL}
        - VPN_ADMIN_PASSWORD=${VPN_ADMIN_PASSWORD}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: admin-bot
    hostname: admin-bot
